import type { FilmPreset, FilmCase, FilterParams } from '@/types'

export const DEFAULT_PARAMS: FilterParams = {
  brightness: 100,
  contrast: 100,
  temperature: 0,
  grain: 0,
  saturate: 100,
  sepia: 0,
  hueRotate: 0,
}

export const FILM_PRESETS: FilmPreset[] = [
  {
    id: 'kodak-portra-400',
    name: 'Portra 400',
    brand: 'Kodak',
    description: '柔和肤色，细腻颗粒，暖调人像首选',
    thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=soft%20warm%20portrait%20film%20grain%20golden%20hour%20skin%20tones&image_size=square',
    params: { brightness: 105, contrast: 95, temperature: 15, grain: 18, saturate: 90, sepia: 8, hueRotate: -2 },
  },
  {
    id: 'kodak-gold-200',
    name: 'Gold 200',
    brand: 'Kodak',
    description: '浓郁暖黄，日常胶卷之王，色彩饱满',
    thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=warm%20golden%20sunset%20vibrant%20colors%20film%20photography&image_size=square',
    params: { brightness: 108, contrast: 105, temperature: 25, grain: 22, saturate: 115, sepia: 12, hueRotate: -5 },
  },
  {
    id: 'fujifilm-superia-400',
    name: 'Superia 400',
    brand: 'Fujifilm',
    description: '偏绿冷调，街拍经典，日系色彩',
    thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cool%20green%20tint%20street%20photography%20japanese%20film%20style&image_size=square',
    params: { brightness: 102, contrast: 98, temperature: -10, grain: 20, saturate: 95, sepia: 3, hueRotate: 5 },
  },
  {
    id: 'fujifilm-pro400h',
    name: 'Pro 400H',
    brand: 'Fujifilm',
    description: '柔和高光，浅蓝偏色，婚纱摄影最爱',
    thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=pastel%20soft%20blue%20wedding%20film%20delicate%20highlight&image_size=square',
    params: { brightness: 110, contrast: 90, temperature: -5, grain: 12, saturate: 85, sepia: 2, hueRotate: 3 },
  },
  {
    id: 'ilford-hp5',
    name: 'HP5 Plus',
    brand: 'Ilford',
    description: '经典黑白，粗犷颗粒，纪实摄影灵魂',
    thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=black%20white%20grainy%20documentary%20film%20noir%20contrast&image_size=square',
    params: { brightness: 100, contrast: 120, temperature: 0, grain: 35, saturate: 0, sepia: 0, hueRotate: 0 },
  },
  {
    id: 'kodak-tri-x',
    name: 'Tri-X 400',
    brand: 'Kodak',
    description: '传奇黑白胶卷，高对比，标志性颗粒',
    thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=iconic%20black%20white%20high%20contrast%20grain%20street%20photography&image_size=square',
    params: { brightness: 95, contrast: 130, temperature: 0, grain: 40, saturate: 0, sepia: 5, hueRotate: 0 },
  },
  {
    id: 'cinestill-800t',
    name: '800T',
    brand: 'CineStill',
    description: '电影感夜景，钨丝灯偏蓝，霓虹梦幻',
    thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cinematic%20neon%20night%20tungsten%20blue%20halation%20dreamy&image_size=square',
    params: { brightness: 95, contrast: 110, temperature: -30, grain: 25, saturate: 110, sepia: 0, hueRotate: 8 },
  },
  {
    id: 'kodak-ektar-100',
    name: 'Ektar 100',
    brand: 'Kodak',
    description: '超饱和色彩，风光利器，红蓝极致',
    thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=vibrant%20saturated%20landscape%20red%20blue%20ultra%20color%20film&image_size=square',
    params: { brightness: 100, contrast: 115, temperature: 10, grain: 8, saturate: 135, sepia: 0, hueRotate: -3 },
  },
]

export const FILM_CASES: FilmCase[] = [
  {
    id: 'case-portra-wedding',
    filmName: 'Kodak Portra 400',
    style: '婚礼人像',
    description: 'Portra 400 柔和的肤色还原与细腻颗粒，是婚礼摄影师的不二之选。暖调偏色带来天然的好气色，高光柔和不刺眼。',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=wedding%20bride%20soft%20warm%20light%20portra%20film%20grain%20romantic&image_size=landscape_4_3',
    params: { brightness: 105, contrast: 92, temperature: 18, grain: 16, saturate: 88, sepia: 10, hueRotate: -2 },
  },
  {
    id: 'case-trix-street',
    filmName: 'Kodak Tri-X 400',
    style: '街头纪实',
    description: 'Tri-X 的高对比度与粗犷颗粒赋予街头摄影戏剧性张力，黑白影调下的城市光影更富故事感。',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=street%20photography%20black%20white%20high%20contrast%20urban%20shadow%20dramatic&image_size=landscape_4_3',
    params: { brightness: 92, contrast: 135, temperature: 0, grain: 45, saturate: 0, sepia: 5, hueRotate: 0 },
  },
  {
    id: 'case-800t-neon',
    filmName: 'CineStill 800T',
    style: '霓虹夜景',
    description: '800T 的钨丝灯白平衡让城市夜景泛出梦幻蓝调，红光晕染（halation）效果让霓虹灯如梦似幻。',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=neon%20city%20night%20blue%20tungsten%20cinematic%20halation%20glow%20dreamy&image_size=landscape_4_3',
    params: { brightness: 92, contrast: 108, temperature: -35, grain: 28, saturate: 115, sepia: 0, hueRotate: 10 },
  },
  {
    id: 'case-pro400h-garden',
    filmName: 'Fujifilm Pro 400H',
    style: '花园写真',
    description: 'Pro 400H 浅蓝偏色配合柔和色调，在户外花园场景中呈现日系清新质感，高光过渡如水彩渲染。',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=garden%20portrait%20pastel%20soft%20blue%20flower%20japanese%20film%20ethereal&image_size=landscape_4_3',
    params: { brightness: 112, contrast: 88, temperature: -8, grain: 10, saturate: 82, sepia: 2, hueRotate: 4 },
  },
  {
    id: 'case-ektar-landscape',
    filmName: 'Kodak Ektar 100',
    style: '风光大片',
    description: 'Ektar 100 的极致饱和度让天空更蓝、草地更绿、落日更红，是风光摄影的终极武器。',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=vivid%20landscape%20mountain%20sunset%20ultra%20saturated%20blue%20sky%20film&image_size=landscape_4_3',
    params: { brightness: 100, contrast: 118, temperature: 12, grain: 6, saturate: 140, sepia: 0, hueRotate: -4 },
  },
  {
    id: 'case-hp5-documentary',
    filmName: 'Ilford HP5 Plus',
    style: '人文纪实',
    description: 'HP5 Plus 在弱光下依然出色，灰阶过渡丰富，颗粒自然不造作，适合记录真实的人文瞬间。',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=documentary%20people%20black%20white%20natural%20grain%20low%20light%20authentic&image_size=landscape_4_3',
    params: { brightness: 98, contrast: 118, temperature: 0, grain: 32, saturate: 0, sepia: 3, hueRotate: 0 },
  },
]
